# Processing mesh
# NOTE: prefix 1- and 2- is used for avoiding duplicated task names

1-get_scale_info:
  input_path: ${data.input_template}
  output_path: ${data.output_template}/info/scale.json

1-mesh_change_format_and_normalize: 
  input_path: ${data.input_template}
  input_scale_path: ${data.output_template}/info/scale.json
  output_path: ${data.output_template}/processed/normalized.obj  
  keep_material: False

1-mesh_convex_decomp:
  input_path: ${data.output_template}/processed/normalized.obj
  output_path: ${data.output_template}/processed/coacd_raw.obj
  quiet: True

1-mesh_remove_small_piece:
  input_path: ${data.output_template}/processed/coacd_raw.obj
  output_path: ${data.output_template}/processed/coacd.obj
  min_volume: 1e-5

1-export_urdf: 
  input_path: ${data.output_template}/processed/coacd.obj
  export_mesh: True
  output_path: ${data.output_template}/urdf/coacd.urdf

1-mesh_manifold:
  input_path: ${data.output_template}/processed/coacd.obj
  output_path: ${data.output_template}/processed/manifold.obj
  quiet: True

1-mesh_simplify:
  input_path: ${data.output_template}/processed/manifold.obj
  output_path: ${data.output_template}/processed/simplified_500.ply  # NOTE: this must be a ply
  vert_num: 500
  gradation: 1.5    # This is recommanded in official repo
  quiet: True

2-mesh_change_format: 
  input_path: ${data.output_template}/processed/simplified_500.ply
  output_path: ${data.output_template}/processed/simplified_500.obj  
  keep_material: False

# Processing info
1-get_basic_info:
  input_path: ${data.output_template}/processed/simplified_500.obj
  output_path: ${data.output_template}/info/simplified.json
